apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "open-discogs-api.fullname" . }}
  labels:
    {{- include "open-discogs-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "open-discogs-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "open-discogs-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "open-discogs-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.api.port | default 8080 }}
              protocol: TCP
            - name: management
              containerPort: {{ .Values.service.management.port | default 8081 }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: management
          readinessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: management
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: management
            periodSeconds: 5
            failureThreshold: 30
          env:
            {{- if .Values.otel.propagators }}
            - name: OTEL_PROPAGATORS
              value: {{.Values.otel.propagators}}
            {{- end}}
            {{- if .Values.otel.service.instance.id }}
            - name: OTEL_SERVICE_INSTANCE_ID
              value: {{.Values.otel.service.instance.id}}
            {{- else}}
            - name: OTEL_SERVICE_INSTANCE_ID
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- end}}
            {{- if .Values.otel.service.name }}
            - name: OTEL_SERVICE_NAME
              value: {{ .Values.otel.service.name }}
            {{- end }}
            {{- if .Values.otel.service.version }}
            - name: OTEL_SERVICE_VERSION
              value: {{ .Values.otel.service.version }}
            {{- else}}
            - name: OTEL_SERVICE_VERSION
              value: {{ .Values.image.tag}}
            {{- end }}
            {{- if .Values.otel.service.namespace }}
            - name: OTEL_SERVICE_NAMESPACE
              value: {{ .Values.otel.service.namespace }}
            {{- end }}
            {{- if .Values.otel.log.level }}
            - name: OTEL_LOG_LEVEL
              value: {{ .Values.otel.log.level }}
            {{- end}}
            {{- if .Values.otel.resource.attributes }}
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: {{.Values.otel.resource.attributes}}
            {{- end}}
            {{- if .Values.otel.traces.exporter }}
            - name: OTEL_TRACES_EXPORTER
              value: {{.Values.otel.traces.exporter}}
            {{- end}}
            {{- if .Values.otel.traces.sampler }}
            - name: OTEL_TRACES_SAMPLER
              value: {{.Values.otel.traces.sampler}}
            {{- end}}
            {{- if .Values.otel.traces.args }}
            - name: OTEL_TRACES_ARGS
              value: {{.Values.otel.traces.args}}
            {{- end}}
            {{- if .Values.otel.metrics.exporter}}
            - name: OTEL_METRICS_EXPORTER
              value: {{.Values.otel.metrics.exporter}}
            {{- end}}
            {{- if .Values.otel.metrics.examplar}}
            - name: OTEL_METRICS_EXAMPLAR_FILTER
              value: {{ .Values.otel.metrics.examplar.filter}}
            {{- end}}
            {{- if .Values.otel.logs.exporter}}
            - name: OTEL_LOGS_EXPORTER
              value: {{.Values.otel.logs.exporter}}
            {{- end}}
            {{- if .Values.otel.sdk.disabled }}
            - name: OTEL_SDK_DISABLED
              value: {{.Values.otel.sdk.disabled | quote }}
            {{- end}}
            {{- if .Values.application.name}}
            - name: SPRING_APPLICATION_NAME
              value: {{ .Values.application.name }}
            {{- else}}
            - name: SPRING_APPLICATION_NAME
              value: open-discogs-api
            {{- end}}
            - name: API_DB_HOST
              value: {{ required "application.database.host cannot be empty or nil" .Values.application.database.host }}
            - name: API_DB_USERNAME
              value: {{ required "application.database.user cannot be empty or nil" .Values.application.database.user }}
            - name: API_DB_PASSWORD
              value: {{ required "application.database.pass cannot be empty or nil" .Values.application.database.pass }}
            {{- if .Values.application.url }}
            - name: API_SERVER_URL
              value: {{ .Values.application.url }}
            {{- else}}
            - name: API_SERVER_URL
              value: 'localhost:8080'
            {{- end}}
            {{- if .Values.application.api.port }}
            - name: SERVER_PORT
              value: {{ .Values.application.api.port | quote }}
            {{- else}}
            - name: SERVER_PORT
              value: '8080'
            {{- end}}
            {{- if .Values.application.management.port }}
            - name: MANAGEMENT_SERVER_PORT
              value: {{ .Values.application.management.port | quote }}
            {{- else}}
            - name: MANAGEMENT_SERVER_PORT
              value: '8081'
            {{- end}}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
